DROP SCHEMA PUBLIC CASCADE;
SET DATABASE TRANSACTION CONTROL MVCC;


CREATE TABLE "PUBLIC"."PROCESSES" (
	"PROCESS_ID" INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1000) PRIMARY KEY,
	"PROCESS_KEY" VARCHAR(255) NOT NULL 
);

CREATE TABLE "PUBLIC"."PROJECT_PROPERTIES" (
	"PROPERTY_ID" INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1000) PRIMARY KEY,
	"PROPERTY_KEY" VARCHAR(255) NOT NULL,
	"PROPERTY_VALUE" VARCHAR(255) NOT NULL,
	"PROCESS_ID" INTEGER,
	CONSTRAINT "FK_PROJECT_PROPERTIES_PROCESSES" FOREIGN KEY ("PROCESS_ID") REFERENCES "PUBLIC"."PROCESSES" ("PROCESS_ID")
);


CREATE TABLE "PUBLIC"."RASTER_LAYERS" (
	"RASTER_LAYER_ID" INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1000) PRIMARY KEY,
	"RASTER_LAYER_PATH" VARCHAR(512) NOT NULL
);

CREATE TABLE "PUBLIC"."RASTER_PROPERTIES" (
	"RASTER_LAYER_ID" INTEGER NOT NULL,
	"RASTER_NORTH" DOUBLE,
	"RASTER_SOUTH" DOUBLE,
	"RASTER_EAST" DOUBLE,
	"RASTER_WEST" DOUBLE,
	"LATITUDE_RESOLUTION" DOUBLE,
	"LONGITUDE_RESOLUTION" DOUBLE,
	"IMAGE_WIDTH" INTEGER,
	"IMAGE_HEIGHT" INTEGER,
	"NUMBER_OF_BANDS" INTEGER,
	"HEADER_SIZE" INTEGER,
	"RASTER_DATA_TYPE" VARCHAR(100),
	"RASTER_BYTE_ORDER" VARCHAR(100),
	"RASTER_INTERLEAVING_TYPE" VARCHAR(100),
	"RASTER_NODATA_VALUE" DOUBLE,
	"RASTER_DEF_LOCKED" BOOLEAN,
	CONSTRAINT "FK_RASTER_LAYER_ID" FOREIGN KEY ("RASTER_LAYER_ID") REFERENCES "PUBLIC"."RASTER_LAYERS" ("RASTER_LAYER_ID")
);

CREATE TABLE "PUBLIC"."MODELGRID_LAYER" (
	"MODELGRID_LAYER_ID" INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1000) PRIMARY KEY,
	"MODELGRID_LAYER_PATH" VARCHAR(512) NOT NULL
);


CREATE TABLE "PUBLIC"."SHAPE_LAYER" (
	"SHAPE_LAYER_ID" INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1000) PRIMARY KEY,
	"SHAPE_LAYER_PATH" VARCHAR(512) NOT NULL,
	"SHAPE_DATA_DEFINITION_ID" VARCHAR(100)
);

CREATE TABLE "PUBLIC"."SIMPLE_GEO_IMAGE_LAYER" (
	"IMAGE_LAYER_ID" INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1000) PRIMARY KEY,
	"IMAGE_LAYER_PATH" VARCHAR(512) NOT NULL,
	"IMAGE_NORTH" DOUBLE,
	"IMAGE_SOUTH" DOUBLE,
	"IMAGE_EAST" DOUBLE,
	"IMAGE_WEST" DOUBLE
);