package us.wthr.jdem846ui.project;

public enum IconEnum
{
	RASTER_DATA,
	SHAPE_DATA,
	IMAGE_DATA,
	MODELGRID_DATA,
	RENDERED_MODEL_OBJECT,
	DATA_SOURCE_CATEGORY,
	RENDERED_MODEL_CATEGORY,
	RASTER_CATEGORY,
	SHAPE_CATEGORY,
	IMAGE_CATEGORY,
	MODELGRID_CATEGORY,
	NONE
}
