package us.wthr.jdem846.graphics;

public enum RenderCodesEnum {
	
	RENDER_NO_ERROR,
	RENDER_ERR_NO_FRAME_BUFFER_DEFINED,
	RENDER_ERR_INVALID_DIMENSIONS,
	RENDER_ERR_INVALID_OPERATION,
	RENDER_ERR_INVALID_TEXTURE,
	RENDER_ERR_INVALID_ENUM,
	
}
